construction/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/',include('projectsite.urls')),
    path('',include('frontsite.urls')),
  
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

frontsite/urls.py
from django.contrib import admin
from django.urls import path
from frontsite import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/',views.register,name='register'),
    path('',auth_views.LoginView.as_view(template_name='frontsite/login.html'),name='login'),
    path('profile/',views.profile,name='profile'),
    path('logout',auth_views.LogoutView.as_view(template_name='frontsite/logout.html'),name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

   

projectsite/urls.py
from django.urls import path
from django.views.generic import TemplateView
from projectsite import views

urlpatterns = [
    path('client/create/', views.client_create_view, name='client_create'),
    path('client/<int:client_id>/', views.client_details, name='client_details'),
    path('client/edit/<int:client_id>/', views.client_edit_view, name='client_edit'),
    path('client/delete/<int:client_id>/',views.client_delete_view, name='client_delete'),
    path('clients/', views.client_list, name='client_list'),
    path('client/dashboard/', views.client_dashboard_view, name='client_dashboard_view'),
    path('status-update/<int:project_id>/',views.status_update_view, name='status_update'),
    path('success/', TemplateView.as_view(template_name='projectsite/success.html'), name='success'),
    # url for project
    path('project/<int:project_id>/', views.project_details, name='project_details'),
    path('projects/add/', views.project_add_view, name='project_add'),
    path('projects/client/<int:client_id>/', views.project_list_by_client, name='project_list_by_client'),
    path('project/<int:project_id>/edit/', views.project_edit_view, name='project_edit'),
    path('project/<int:project_id>/delete/', views.project_delete_view, name='project_delete'),
    path('dashboard/',views. project_dashboard_view, name='project_dashboard_view'),
    path('projects/', views.project_list, name='project_list'),
    path('project/<int:project_id>/stages/', views.stage_list, name='stage_list'),
    # url for stages
    path('stage/<int:id>/', views.stage_details, name='stage_details'),
    path('project/<int:project_id>/stages/add/', views.stage_add, name='stage_add'),
    path('stage/<int:stage_id>/edit/', views.stage_edit, name='stage_edit'),
    path('stage/<int:stage_id>/delete/', views.stage_delete, name='stage_delete'),
    path('stage_list/<int:project_id>/', views.stage_list, name='stage_list'),
    #url for expense
    path('projects/<int:project_id>/expenses/', views.expense_list, name='expense_list'),
    path('projects/<int:project_id>/expenses/new/', views.expense_new, name='expense_new'),
    path('projects/<int:project_id>/expenses/<int:expense_id>/', views.expense_details, name='expense_details'),
    path('projects/<int:project_id>/expenses/<int:expense_id>/edit/', views.expense_edit, name='expense_edit'),
    path('projects/<int:project_id>/expenses/<int:expense_id>/delete/', views.expense_delete, name='expense_delete'),
]

projectsite/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default='')
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    site_location = models.CharField(max_length=200)
    site_name = models.CharField(max_length=100)
    project_start_date = models.DateField()
    project_end_date = models.DateField()
    project_duration = models.IntegerField(editable=False, null=True)  # Auto-calculated
    documents = models.FileField(upload_to='documents/', null=True, blank=True)

    def save(self, *args, **kwargs):
        self.project_duration = (self.project_end_date - self.project_start_date).days
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Project(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    budget = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()

    def __str__(self):
        return self.name


class Stage(models.Model):
    STAGE_CHOICES = [
        ('ceiling', 'Ceiling'),
        ('flooring', 'Flooring'),
        ('plumbing', 'Plumbing'),
        ('painting', 'Painting'),
        ('foundation', 'Foundation'),
        ('framing', 'Framing'),
        ('electrical', 'Electrical'),
        ('hvac', 'HVAC'),
        ('roofing', 'Roofing'),
        ('drywall', 'Drywall'),
        ('insulation', 'Insulation'),
        ('siding', 'Siding'),
        ('windows', 'Windows'),
        ('doors', 'Doors'),
        ('landscaping', 'Landscaping'),
        ('finishing', 'Finishing'),
        ('furniture_installation', 'Furniture Installation'),
        ('final_touchups', 'Final Touch-ups')
    ]
    COMPLETED_CHOICES = [
        ('C', 'Completed'),
        ('NC', 'Not Completed'),
        ('P', 'Pending')
    ]
    STATUS_CHOICES = [
        ('not_started', 'Not Started'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('on_hold', 'On Hold'),
    ]

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='stages')
    name = models.CharField(max_length=100)
    due_date = models.DateField()
    completed = models.CharField(max_length=2, choices=COMPLETED_CHOICES, default='P')
    progress = models.IntegerField(default=0)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    stage_type = models.CharField(max_length=50, choices=STAGE_CHOICES)
   

    def __str__(self):
        return f"{self.stage_type} - {self.project.name}"

class Expense(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="Project")
    stage = models.ForeignKey(Stage, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Stage")
    description = models.TextField()
    amount_spent = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Amount Spent")
    date = models.DateField(verbose_name="Date")

    class Meta:
        ordering = ['date']
        verbose_name = "Expense"
        verbose_name_plural = "Expenses"

    def __str__(self):
        return f"{self.date} - {self.project.name} - {self.stage.stage_type if self.stage else 'No Stage'}"

projectsite/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ClientForm, ProjectForm,StageForm,ExpenseForm
from .models import Client, Project, Stage, Expense
from django.contrib.auth.decorators import login_required
import json



@login_required
def client_create_view(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
                client = form.save(commit=False)
                client.user = request.user  # Assign the current logged-in user to the user field
                client.save()

        return redirect('client_list')
    else:
        form = ClientForm()
    return render(request, 'projectsite/client_create.html', {'form': form})


@login_required
def client_details(request, client_id):
    client = Client.objects.get(id=client_id, user=request.user)
    return render(request, 'projectsite/client_details.html', {'client': client})




@login_required
def client_edit_view(request, client_id):
    client = get_object_or_404(Client, id=client_id, user=request.user)
    
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form = ClientForm(instance=client)
        
    return render(request, 'projectsite/client_edit.html', {'form': form, 'client': client})




@login_required
def client_delete_view(request, client_id):
    client =Client.objects.get(id=client_id, user=request.user)
    
    if request.method == 'POST':
        client.delete()
        return redirect('client_list')
        
    return render(request, 'projectsite/client_delete.html', {'client': client})

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Client, Project, Stage, Expense, User
import json

@login_required
def admin_dashboard_view(request):
    # User Statistics
    user_count = User.objects.count()
    active_users = User.objects.filter(is_active=True).count()
    new_users = User.objects.filter(date_joined__month='current_month').count()  # Adjust the date filter as needed

    # Project Statistics
    total_projects = Project.objects.count()
    ongoing_projects = Project.objects.filter(status='ongoing').count()
    completed_projects = Project.objects.filter(status='completed').count()

    # Client Information
    total_clients = Client.objects.count()

    # Data for Charts
    project_names = [project.name for project in Project.objects.all()]
    budgets = [float(project.budget) for project in Project.objects.all()]
    total_spents = [float(sum(expense.amount_spent for expense in Expense.objects.filter(project=project))) for project in Project.objects.all()]

    context = {
        'user_count': user_count,
        'active_users': active_users,
        'new_users': new_users,
        'total_projects': total_projects,
        'ongoing_projects': ongoing_projects,
        'completed_projects': completed_projects,
        'total_clients': total_clients,
        'project_names': json.dumps(project_names),
        'budgets': json.dumps(budgets),
        'total_spents': json.dumps(total_spents),
    }
    return render(request, 'projectsite/admindashboard.html', context)


@login_required
def client_dashboard_view(request):
    clients = Client.objects.filter(user=request.user)  # Retrieve all clients associated with the logged-in user
   
    
    projects = Project.objects.filter(client__in=clients)
    stages = Stage.objects.filter(project__in=projects)
    expenses = Expense.objects.filter(project__in=projects)

    project_names = [project.name for project in projects]
    budgets = [float(project.budget) for project in projects]
    total_spents = [float(sum(expense.amount_spent for expense in Expense.objects.filter(project=project))) for project in projects]

    context = {
        'clients': clients,
        'projects': projects,
        'project_names': json.dumps(project_names),
        'budgets': json.dumps(budgets),
        'total_spents': json.dumps(total_spents),
        'stages': stages,
        'expenses': expenses,
    }
    return render(request, 'projectsite/clientdashboard.html', context)

def client_list(request):
    clients = Client.objects.all()
    return render(request, 'projectsite/client_list.html', {'clients': clients})


# List all projects
def project_list(request):
    projects = Project.objects.all()
    return render(request, 'projectsite/project_list.html', {'projects': projects})

# View details of a single project
def project_details(request, project_id):
    project = Project.objects.get( pk=project_id)
    return render(request, 'projectsite/project_details.html', {'project': project})

# Create a new project
def project_add_view(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('project_list')
    else:
        form = ProjectForm()
    return render(request, 'projectsite/project_add.html', {'form': form})

# Edit an existing project
def project_edit(request, pk):
    project = Project.objects.get( pk=pk)
    if request.method == "POST":
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('project_detail', pk=pk)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'projectsite/project_form.html', {'form': form})



@login_required
def project_list_view(request):
    projects = Project.objects.filter(client__user=request.user)
    return render(request, 'projectsite/project_list.html', {'projects': projects})


@login_required
def project_edit_view(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('/site/success/')  # Change to your success URL
    else:
        form = ProjectForm(instance=project)
    return render(request, 'projectsite/project_edit.html', {'form': form})


@login_required
def project_delete_view(request, project_id):
    project = Project.objects.get(id=project_id)
    if request.method == 'POST':
        project.delete()
        return redirect('project_list')  # Change to your success URL
    return render(request, 'projectsite/project_delete.html', {'project': project})


def project_list_by_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    projects = Project.objects.filter(client=client)
    return render(request, 'projectsite/project_list_by_client.html', {'client': client, 'projects': projects})

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Client, Project, Expense

@login_required
def project_dashboard_view(request):
    clients = Client.objects.filter(user=request.user)  # Retrieve all clients associated with the logged-in user
    if not clients.exists():
        # Redirect to a page where user can create a Client profile or display a friendly message
        return render(request, 'projectsite/no_client.html')
    
    projects = Project.objects.filter(client__in=clients)
    project_names = [project.name for project in projects]
    budgets = [float(project.budget) for project in projects]
    total_spents = [float(sum(expense.amount_spent for expense in Expense.objects.filter(project=project))) for project in projects]

    context = {
        'clients': clients,
        'projects': projects,
        'project_names': project_names,  # Pass the list directly
        'budgets': budgets,  # Pass the list directly
        'total_spents': total_spents,  # Pass the list directly
    }
    return render(request, 'projectsite/projectdashboard.html', context)


def stage_list(request, project_id):
    project = Project.objects.get( id=project_id)
    stages = Stage.objects.filter(project=project)
    return render(request, 'projectsite/stage_list.html', {'project': project, 'stages': stages})



def stage_details(request, id):
    project = get_object_or_404(Project, id=id)
    stages = Stage.objects.filter(project=project)
    return render(request, 'projectsite/stage_details.html', {'project': project, 'stages': stages})

def stage_add(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = StageForm(request.POST)
        if form.is_valid():
            stage = form.save(commit=False)
            stage.project = project
            stage.save()
            return redirect('stage_list', project_id=project_id)
    else:
        form = StageForm()
    return render(request, 'projectsite/stage_add.html', {'form': form, 'project': project})

def stage_edit(request, stage_id):
    stage = get_object_or_404(Stage, id=stage_id)
    if request.method == 'POST':
        form = StageForm(request.POST, instance=stage)
        if form.is_valid():
            form.save()
            return redirect('stage_detail', stage_id=stage_id)
    else:
        form = StageForm(instance=stage)
    return render(request, 'projectsite/stage_edit.html', {'form': form})

def stage_delete(request, stage_id):
    stage = Stage.objects.get( id=stage_id)
    if request.method == 'POST':
        stage.delete()
        return redirect('stage_list', project_id=stage.project.id)
    return render(request, 'projectsite/stage_delete.html', {'stage': stage})


#Add new expense
def expense_new(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == "POST":
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.project = project
            expense.save()

construction/templates/projectsite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaf Construction</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'css/leaf.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Top Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'profile' %}">Profile</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Sidebar -->
    <div class="d-flex">
        <div class="d-flex flex-column flex-shrink-0 p-3 sidebar-custom text-white">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <span class="fs-4">Sidebar</span>
            </a>
            <hr>
            {% if user.is_authenticated %}
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#dashboardSubMenu" role="button" aria-expanded="false" aria-controls="dashboardSubMenu">
                        <i class="fas fa-tools"></i> Dashboard
                    </a>
                    <div class="collapse" id="dashboardSubMenu">
                        <ul class="submenu list-unstyled ps-3">
                            <li><a href="index.html" class="text-white">Admin Dashboard</a></li>
                            <li><a href="{% url 'project_dashboard_view' %}" class="text-white">Project Dashboard</a></li>
                            <li><a href="{% url 'client_dashboard_view' %}" class="text-white">Client Dashboard</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#projectsSubMenu" role="button" aria-expanded="false" aria-controls="projectsSubMenu">
                        <i class="fas fa-hard-hat"></i> Projects
                    </a>
                    <div class="collapse" id="projectsSubMenu">
                        <ul class="submenu list-unstyled ps-3">
                            <li><a href="{% url 'project_list' %}" class="text-white">Project List</a></li>
                            <li><a href="{% url 'project_add' %}" class="text-white">Project Add</a></li>
                            <!--i included stages here-->
                            {% if project %}
                            <li><a href="{% url 'stage_details' project.id %}" class="text-white">Project Stages</a></li>
                            {% endif %}
                        
                        </ul>
                    </div>
                    
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#clientsSubMenu" role="button" aria-expanded="false" aria-controls="clientsSubMenu">
                        <i class="fas fa-users"></i> Clients
                    </a>
                    <div class="collapse" id="clientsSubMenu">
                        <ul class="submenu list-unstyled ps-3">
                            <li><a href="{% url 'client_list' %}" class="text-white">Client List</a></li>
                            <li><a href="{% url 'client_create' %}" class="text-white">Client Add</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
            
            {% else %}
            <ul class="nav nav-pills flex-column mb-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'profile' %}">Profile</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active m-2" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active m-2" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
            <hr>
        </div>

        <div class="content p-4">
            <!-- Content for each page will be injected here -->
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>



    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    {% block scripts %}{% endblock %}
</body>
</html>

construction/templates/projectsite/client_create.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}Create Client{% endblock %}

{% block content %}
    <h1>Client List</h1>
    <h2>Create Client</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
{% endblock %}

construction/templates/projectsite/client_delete.html
<!-- client_onboarding.html -->
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}Delete Client{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Are you sure you want to delete this client?</h1>
    <p><strong>Client Name:</strong> {{ client.name }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'client_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

construction/templates/projectsite/client_list.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}>Client List<{% endblock %}

{% block content %}
    <div class="container-fluid m-1 new">
        <h1>Client List</h1>
        <table class="table  table-striped table-hover table-bordered ">
          
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Site Location</th>
                    <th>Site Name</th>
                    <th>Project Start Date</th>
                    <th>Project End Date</th>
                    <th>Project Duration</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                <tr>
                    <td>{{ client.name }}</td>
                    <td>{{ client.phone_number }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.site_location }}</td>
                    <td>{{ client.site_name }}</td>
                    <td>{{ client.project_start_date }}</td>
                    <td>{{ client.project_end_date }}</td>
                    <td>{{ client.project_duration }} days</td>
                    <td style="width: 300px;">
                        <a href="{% url 'project_list_by_client' client.id %}" class="btn btn-primary btn-sm p-2">View Projects</a>
                        <a href="{% url 'client_edit' client.id %}" class="btn btn-warning btn-sm p-2">Update</a>
                        <a href="{% url 'client_delete' client.id %}" class="btn btn-danger btn-sm p-2 m-1" >Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'client_create' %}" class="btn btn-primary fs-4">Add New Client</a>
            </div>
{% endblock %}

construction/templates/projectsite/expense_details.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}Expense Details{% endblock %}
{% block content %}
  <h1>Expense Details</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Description</th>
        <th>Amount Spent</th>
        <th>Date</th>
        <th>Project</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ expense.description }}</td>
        <td>{{ expense.amount_spent }}</td>
        <td>{{ expense.date }}</td>
        <td>{{ project.name }}</td>
        <td><a href="{% url 'expense_edit' project.id expense.id %}">Edit</a>
          <a href="{% url 'expense_list' project.id %}">Back to list</a></td>
      </tr>
    </tbody>
  </table>
{% endblock %}

construction/templates/projectsite/no_client.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}no client{% endblock %}

{% block content %}
    <div class="container">
        <h1>Welcome!</h1>
        <p>It looks like you don't have any client profiles yet.</p>
        <a href="{% url 'client_create' %}" class="btn btn-primary">Create Client Profile</a>
    </div>
{%endblock%}

construction/templates/projectsite/project_edit.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}Edit Project{% endblock %}
{%block content%}
    
    <h1>Edit Project</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

construction/templates/projectsite/stage_details.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<h1>Project: {{ stages.0.project.name }}</h1>  <!-- Display the project name from the first stage object -->
<table class="table table-striped table-bordered">
    <thead>
        <tr>  
            <th>Project</th>
            <th>Due Date</th>
            <th>Completed</th>
            <th>Progress</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Stage Type</th>
        </tr>
    </thead>
    <tbody>
        {% for stage in stages %}
        <tr>
            <td>{{ stage.project.name }}</td>  <!-- Adjusted to access the project's name -->
            <td>{{ stage.due_date }}</td>
            <td>{{ stage.get_completed_display }}</td>
            <td>{{ stage.progress }}%</td>
            <td>{{ stage.start_date }}</td>
            <td>{{ stage.end_date }}</td>
            <td>{{ stage.get_stage_type_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

construction/templates/projectsite/stage_list.html
{% extends 'projectsite/base.html' %}
{% block title %}Stage List{% endblock %}
{% block content %}
    <h1>Stages for Project: {{ project.name }}</h1>
    <table class="table table-striped table-bordered table-hover" style="width: 750px; text-align:center;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Due Date</th>
                <th>Completed</th>
                <th>Progress</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for stage in stages %}
            <tr>
                <td><a href="{% url 'stage_details' stage.id %}">{{ stage.name }}</a></td>
                <td>{{ stage.due_date }}</td>
                <td>{{ stage.get_completed_display }}</td>
                <td>{{ stage.progress }}%</td>
                <td>
                    <a href="{% url 'stage_edit' stage.id %}" class="btn btn-warning btn-sm ms-2">Update</a>
                    <a href="{% url 'stage_delete' stage.id %}" class="btn btn-danger btn-sm ms-4">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'stage_add' project.id %}" class="btn btn-primary">Add New Stage</a>
{% endblock %}